openapi: 3.0.0
info:
  title: skitfarm api
  description: This api enebales access to publish and subscribe endpoints
  version: 0.1.9
servers:
  - url: http://kenyacovid.azurewebsites.net/
    description: Main server
  - url: http://127.0.0.1:5000/
    description: Testing server at local computer
paths:
  /subscribe:
    get:
      summary: Get the published message from the MQTT serve
      description: subscribe to what is in the topics
      responses:
        '200':    # status code
          description: A JSON file for kenya data at the current date
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string